spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/KrainetDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  rabbitmq:
    host: rabbitmq
    port: 5672

jwt:
  secret: ChangeThisToAStrongSecretKey
  expiration-ms: 3600000
