
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/KrainetDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.flyway:
  enabled: true

spring.rabbitmq:
  host: rabbitmq
  port: 5672

jwt:
  secret: VeryVeryStrongSecretKey
  expiration-ms: 3600000    # 1 ???
