spring:
  rabbitmq:
    host: rabbitmq
    port: 5672



notification:
  admin-emails:
    - admin@example.com

management:
  endpoints:
    web:
      exposure:
        include: health,info
  security:
    enabled: false