services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: KrainetDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    ports:
      - "5433:5432"   # (только для доступа с хоста)
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  rabbitmq:
    image: rabbitmq:3-management
    ports: [ "5672:5672","15672:15672" ]
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: auth-service-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/KrainetDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - backend


  notification-service:
    build: ./notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
